### ISSUE TITLE
Update TTS Handbook - new search index and analytics (made from all TTS microsites/guides) on Search.gov

### ISSUE THREAD

**Issue by afeld** [18F/tts-tech-portfolio#450]
## Background

The idea: searching the Handbook should also show results from other non-Handbook-but-still-TTS-facing sites, such as:

- [Before You Ship](https://before-you-ship.18f.gov/)
- [Engineering Practices Guide](https://engineering.18f.gov/)

Of course, another way to approach this would be to consolidate said sites, but that was decided against in https://github.com/18F/before-you-ship/issues/421.

## User stories

- [As someone searching for "ato", I would expect relevant results (from Before You Ship) to show up.](https://gsa-tts.slack.com/archives/C0DCAMLQH/p1580241666039600)

The [Full URLs](https://analytics.google.com/analytics/web/?utm_source=marketingplatform.google.com&utm_medium=et&utm_campaign=marketingplatform.google.com%2Fabout%2Fanalytics%2F#/report-home/a48605964w95119189p117236320) view of the Handbook in Google Analytics is not showing any new data, presumably following 18F/handbook#1452. Unclear where to change that domain, which is presumably filtering out new data.

![Screen Shot 2020-02-07 at 1 50 21 PM](https://user-images.githubusercontent.com/86842/74056883-cf58da80-49b0-11ea-9130-a3b6b9093716.png)

While looking at the site analytics with @UchMok, noticed that the Product Guide is using the same Google Analytics ID as the Handbook, and thus the contents are co-mingled. Doesn't appear I have the permissions to make a new one to quickly fix that, so putting this issue in as a placeholder.

## Acceptance Criteria
- [x] Add jekyll-sitemap plugin to all guides and ~other TTS micro knowledge bases.
- [x] Add all child sites ^ to TTS Handbooks search index via the Search.gov GUI.
- [x] Reindex and Test search results
- [x] verify the final/full list of all sites the search results should return.
- [ ] Make sure analytics.usa.gov and GA dashboard are using the new search.gov sitemap/urls match up and correct Google Analytics code.

**Comment by JJediny** [comment]
**Update**: Work completed to map the content metadata used for each of the sites @hoaiandang will be taking over the implementation work with me as a support to co-work it

cc @afeld @its-a-lisa-at-work to provide prioritization in next sprint.

@hoaiandang the TLDR of this task is adding a sitemap.xml to each site using a jekyll template mapped to the existing frontmatter each site uses.

# 18F Guides (Frontmatter/xml/json feed)
[TOC]

## [18f.gsa.gov](https://18f.gsa.gov)
[GITHUB](https://github.com/18F/18f.gsa.gov)

#### Sitemap.xml
https://github.com/18F/18f.gsa.gov/blob/master/sitemap.xml
```xml
---
---
<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.sitemaps.org/schemas/sitemap/0.9 http://www.sitemaps.org/schemas/sitemap/0.9/sitemap.xsd" xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">

  {% if site.url %}
    {% if site.baseurl == '/site' %}
      {% assign site_url = site.localhost | append: site.baseurl %}
    {% else %}
      {% assign site_url = site.url | append: site.baseurl %}
    {% endif %}
  {% else %}
    {% assign site_url = site.github.url %}
  {% endif %}

  {% for post in site.posts %}{% unless post.sitemap == false %}

  <url>
    <loc>{{ post.url | prepend: site_url }}</loc>
    {% if post.last_modified_at %}
    <lastmod>{{ post.last_modified_at | date_to_xmlschema }}</lastmod>
    {% else %}
    <lastmod>{{ post.date | date_to_xmlschema }}</lastmod>
    {% endif %}
  </url>
  {% endunless %}{% endfor %}
  {% for page in site.html_pages %}{% unless page.sitemap == false %}
  <url>
    <loc>{{ page.url | replace:'/index.html','/' | prepend: site_url }}</loc>
    {% if page.last_modified_at %}
    <lastmod>{{ page.last_modified_at | date_to_xmlschema }}</lastmod>
    {% endif %}
  </url>
  {% endunless %}{% endfor %}
  {% for collection in site.collections %}{% unless collection.last.output == false %}
  {% for doc in collection.last.docs %}{% unless doc.sitemap == false %}
  <url>
    <loc>{{ doc.url | replace:'/index.html','/' | prepend: site_url }}</loc>
    {% if doc.last_modified_at %}
    <lastmod>{{ doc.last_modified_at | date_to_xmlschema }}</lastmod>
    {% endif %}
  </url>
  {% endunless %}{% endfor %}
  {% endunless %}{% endfor %}
  {% for file in site.html_files %}
  <url>
    <loc>{{ file.path | prepend: site_url }}</loc>
    <lastmod>{{ file.modified_time | date_to_xmlschema }}</lastmod>
  </url>
  {% endfor %}
</urlset>
```


## [TTS Handbook](http://handbook.18f.gov/)
[GITHUB](https://github.com/18F/handbook)

```
url: "https://handbook.tts.gsa.gov"
plugins:
  - jekyll-sitemap
```  


## [Before-you-ship](https://before-you-ship.18f.gov/)
[GITHUB](https://github.com/18F/before-you-ship)
```yaml
---
title: Framework-Specific Security Guidelines
navtitle: Frameworks
parent: Security
permalink:
---
```

## [Accessibility](https://pages.18f.gov/accessibility/)
[GITHUB](https://github.com/18F/accessibility)
```yaml
---
title: Alternative versions
description: 'How we deal with Alternative Versions'
permalink: /alternative-versions/
page_title: Alternative versions
layout: post
sidenav: docs
---
```


## [Agile](https://agile.18f.gov/)
[GITHUB](https://github.com/18F/agile/)
```yaml
---
title:  18F Agile based project approach
permalink: /18f-agile-approach/
layout: page
sidenav: sidenav
---
```


## [Content](https://pages.18f.gov/content-guide/)
[GITHUB](https://github.com/18F/content-guide)
```yaml
---
title: Resources
redirect_from:
  - /references/
---
```


## [Design methods](https://methods.18f.gov/) 
[GITHUB](https://github.com/18F/methods)
```yaml
---
layout: card
title: [Title here]
permalink: /[category]/[title-slug]/
redirect_from:
  - /[title-slug]/
description: [Description here — this is the one-line "What"]
category: Discover
what: [Description here — this is the one-line "What"]
why: [Description here - this is a short "Why"]
timeRequired: [Estimated time — can be a range]
governmentConsiderations:
```

## [Engineering](https://engineering.18f.gov/) 
[GITHUB](https://github.com/18F/development-guide)
```yaml
---
title:  18F Agile based project approach
permalink: /18f-agile-approach/
layout: page
sidenav: sidenav
---
```

## [Product](https://product-guide.18f.gov/) 
[GITHUB](https://github.com/18F/product-guide)
```yaml
---
title:  18F Agile based project approach
permalink: /18f-agile-approach/
---
```
